### PR TITLE
Improved grammar

### PR DESCRIPTION
**Pull request by bookchiq**
I tweaked a few phrases to make the English more consistent.

### CODE REVIEW

**Comment by legomushroom** [comment]
Hey! Nice work!) Unfortunately index.html is generated from compiled index.jade so your commit will be overwritten on further iterations. Do you familiar with jade?

**Comment by bookchiq** [comment]
Not yet, but give me about 3 minutes. ;)

**Comment by legomushroom** [comment]
if you got some troubles, I can do it right now) You've make a great contribution already)

**Comment by legomushroom** [comment]
what do you think?

**Pull request closed without merging**
